"""new fields in user maodel

Revision ID: 9617022de710
Revises: 3f7f498cd261
Create Date: 2025-02-07 22:46:20.911353

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9617022de710"
down_revision = "3f7f498cd261"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_seen", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("about_me", sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("about_me")
        batch_op.drop_column("last_seen")

    # ### end Alembic commands ###
